[package]
name = "http-assets"
description = "A library implementation of the IC Assets Canister with v2 certification"
version = "0.2.0"
repository = "https://github.com/edjcase/http-assets"
license = "MIT"
keywords = ["certified", "http", "request", "streaming", "assets"]

[dependencies]
"base@0" = "0.16.0"
"http-types@1" = "1.0.1"
"map@9" = "9.0.1"
"certified-assets@0" = "0.6.0"
"ic@3" = "3.2.0"
"itertools@0" = "0.2.2"
"vector@0" = "0.4.2"
"http-parser@0" = "0.4.1"
"sha2@0" = "0.1.6"
"memory-region@1" = "1.3.2"
"base-x-encoder@2" = "2.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
fuzz = "1.0.0"
serde = "3.3.2"
deflate = "0.1.0"

[toolchain]
wasmtime = "15.0.0"
pocket-ic = "4.0.0"
